<a href="https://colab.research.google.com/github/wonmaungthein/DataScience/blob/main/Worksheets/Data_retrieval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data retrieval
---

Examples of data being retrieved from a range of sources

## From a web page
---

The code below reads all the data tables from the Wikipedia page on Glasgow.  The 8th table on the page shows population data over a period of centuries.

The code reads the data from the page into a list of datatables.  The index [7] is used to access the 8th table in the list.  Change the index to see other data tables.  Use len(datatables) to find out how many tables are in the list.

In [8]:
import pandas as pd

def get_data():
  datatables = pd.read_html('https://en.wikipedia.org/wiki/Glasgow#Climate')
  #  change the line below to look at other tables, add the line print(len(datatables)) to see how many tables there are
  lengthOfTable = len(datatables)
  print('length of talbe :', lengthOfTable)

  populationData = datatables[8]
  print(populationData)
  
  df = datatables[7]  #Glasgow population data
  return df



# run and test the get_data() function, test visually - does it match the data on the web page
get_data()

length of talbe : 25
    Year[74]  ...                                       Area changes
0       1300  ...                                            Initial
1       1600  ...                                            Unknown
2       1791  ...  Anderson to James Street/West Nile Street to C...
3       1831  ...                          Necropolis and Blythswood
4       1846  ...   Burghs of Anderston and Calton/Barony of Gorbals
5       1872  ...  Districts of Keppochhill, Alexandra Parade and...
6       1891  ...  Burghs of Govanhill, Crosshill, Pollokshields,...
7       1901  ...  Bellahouston Park and Craigton. Districts of B...
8       1912  ...  Burghs of Govan, Partick, Pollokshaws. Distric...
9       1921  ...                                          No change
10      1926  ...  Districts of Lambhill, Millerston, Aikenhead, ...
11      1938  ...  Districts of Balmuildy, Auchinairn, Cardowan, ...
12      1946  ...                                          No change
13      1951  ...                                          No change
14      1961  ...                                          No change
15      1971  ...                                          No change
16      1981  ...  Burghs of Rutherglen, Cambuslang, Mount Vernon...
17      1991  ...                              Minor boundary change
18      2001  ...  Rutherglen and Cambuslang transferred to South...
19      2011  ...                              Minor boundary change

[20 rows x 5 columns]

     Historical population of Glasgow and city limits  ...                                         Unnamed: 4
0   Historical population and city limits Year[74]...  ...                                                NaN
1                                            Year[74]  ...                                       Area changes
2                                                1300  ...                                            Initial
3                                                1600  ...                                            Unknown
4                                                1791  ...  Anderson to James Street/West Nile Street to C...
5                                                1831  ...                          Necropolis and Blythswood
6                                                1846  ...   Burghs of Anderston and Calton/Barony of Gorbals
7                                                1872  ...  Districts of Keppochhill, Alexandra Parade and...
8                                                1891  ...  Burghs of Govanhill, Crosshill, Pollokshields,...
9                                                1901  ...  Bellahouston Park and Craigton. Districts of B...
10                                               1912  ...  Burghs of Govan, Partick, Pollokshaws. Distric...
11                                               1921  ...                                          No change
12                                               1926  ...  Districts of Lambhill, Millerston, Aikenhead, ...
13                                               1938  ...  Districts of Balmuildy, Auchinairn, Cardowan, ...
14                                               1946  ...                                          No change
15                                               1951  ...                                          No change
16                                               1961  ...                                          No change
17                                               1971  ...                                          No change
18                                               1981  ...  Burghs of Rutherglen, Cambuslang, Mount Vernon...
19                                               1991  ...                              Minor boundary change
20                                               2001  ...  Rutherglen and Cambuslang transferred to South...
21                                               2011  ...                              Minor boundary change

[22 rows x 5 columns]

## From a local file
---

You can upload from a local file using the code below.  uploaded = file.upload() will open a file chooser and you can choose the data file from there.  After that, just use the file name to read from it.  

The file exists while the notebook is running, so should only be uploaded once.  If you need to access again, cancel the upload.

For this exercise you will need a copy of an Excel file.  To get a copy of this file "public_use-talent-migration.xlsx" go to this page: https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx and click on the Download button.  You will now have a copy in your Downloads folder.

In [32]:
import pandas as pd
from google.colab import files
import io

def get_data():
  # upload a set of chosen files then read a specified file
  uploaded = files.upload()
  df = pd.read_excel(uploaded['public_use-talent-migration.xlsx'],sheet_name="Industry Migration")
  return df



# run and test the get_data() function, test visually - does it match the data on the web page
get_data()

MessageError: ignored

## From a csv file hosted on Github.com
---

The code below reads the data table stored in a Comma Separated Values file (this is a text file containing rows of data with each column within the row separated from the next column by a comma).  

If you were using Jupyter Notebooks on your device, the url could be replaced with the path to the CSV file.

In [12]:
import pandas as pd
url = "https://raw.githubusercontent.com/futureCodersSE/working-with-data/main/Data%20sets/Paisley-Weather-Data.csv"
df = pd.read_csv(url)
df

     yyyy  mm tmax (degC)  ... rain (mm) sun (hours)       status
0    1959   1           4  ...      40.9        54.1          NaN
1    1959   2         6.6  ...      41.8        17.8          NaN
2    1959   3        10.6  ...      50.9        85.7          NaN
3    1959   4          13  ...      76.3       125.1          NaN
4    1959   5        18.1  ...        24         222          NaN
..    ...  ..         ...  ...       ...         ...          ...
741  2020  10       12.9*  ...    185.3*       76.8*  Provisional
742  2020  11       10.6*  ...    142.4*       29.3*  Provisional
743  2020  12        6.9*  ...    131.0*       31.6*  Provisional
744  2021   1        4.9*  ...    132.2*       51.0*  Provisional
745  2021   2        7.0*  ...    144.3*       58.8*  Provisional

[746 rows x 8 columns]

## From an Excel file hosted on Github.com
---

The code below reads the data table from a sheet in an Excel file.  If you don't specify a sheet then it will assume that you want to read the data from the first sheet in the Excel workbook (sheet_name = 0).  If you don't know the sheet name but know it is the second sheet, you can use sheet_name = 1, or 2 for the third sheet, etc.

If you were using Jupyter Notebooks on your device, the url could be replace with the path to the Excel file.

In [17]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name="Industry Migration")
dfSecondPage = pd.read_excel(url,sheet_name=1)
print(dfSecondPage)
print('first page :', df)

    Unnamed: 0 Unnamed: 1  Unnamed: 2  ...  Unnamed: 15  Unnamed: 16  Unnamed: 17
0          NaN        NaN         NaN  ...          NaN          NaN          NaN
1          NaN        NaN         NaN  ...          NaN          NaN          NaN
2          NaN        NaN         NaN  ...          NaN          NaN          NaN
3          NaN        NaN         NaN  ...          NaN          NaN          NaN
4          NaN      Notes         NaN  ...          NaN          NaN          NaN
..         ...        ...         ...  ...          ...          ...          ...
72         NaN        NaN         NaN  ...          NaN          NaN          NaN
73         NaN        NaN         NaN  ...          NaN          NaN          NaN
74         NaN        NaN         NaN  ...          NaN          NaN          NaN
75         NaN        NaN         NaN  ...          NaN          NaN          NaN
76         NaN        NaN         NaN  ...          NaN          NaN          NaN

[77 rows x 18 columns]
first page :      country_code          country_name  ... net_per_10K_2018 net_per_10K_2019
0              ae  United Arab Emirates  ...            68.51            49.55
1              ae  United Arab Emirates  ...           149.57           182.22
2              ae  United Arab Emirates  ...           409.18           407.41
3              ae  United Arab Emirates  ...           236.69           188.07
4              ae  United Arab Emirates  ...           852.39           519.40
...           ...                   ...  ...              ...              ...
5290           zw              Zimbabwe  ...            70.60           -18.30
5291           zw              Zimbabwe  ...          -234.59          -304.36
5292           zw              Zimbabwe  ...           311.03           -55.88
5293           zw              Zimbabwe  ...          -108.16          -213.82
5294           zw              Zimbabwe  ...           -39.32           -92.51

[5295 rows x 13 columns]

## From an API which delivers the data in JSON format
---

The code below requests the data from the url.  This is a bit more tricky than the other ways to get the data as how you access the data will depend on how it is organised.

In this example, the data is returned as a dictionary, which will have the key 'data' against which the actual data is stored.  In the example, the data has been taken from the 'data' key/value pair and is stored in json_data. 

Again, in this example, the json_data is a list of json_objects but it only has one object in the list.  Try adding the line `print(json_data)` to see this.  

data_table is the first object in the json_data list.  Try adding the line `print(data_table)` to see this.

In this example, the data table object has three keys, 'to', 'from' and 'regions'.  The 'regions' value is the data we want to use in our dataframe, so we normalize this json data into a pandas dataframe (df), which you can see as the output.  

Each API is likely to deliver its data in a different format and so you will need to be happy to read the documentation and to inspect the data to see what keys and indexes you need to access.

For information on the format of the data, see https://carbon-intensity.github.io/api-definitions/#regional

In [22]:
import pandas as pd
import requests

url = "https://api.carbonintensity.org.uk/regional"
json_data = requests.get(url).json()['data']
data_table = json_data[0]
df = pd.json_normalize(data_table['regions'])

print(json_data)
print(data_table)

df

[{'from': '2021-09-29T09:00Z', 'to': '2021-09-29T09:30Z', 'regions': [{'regionid': 1, 'dnoregion': 'Scottish Hydro Electric Power Distribution', 'shortname': 'North Scotland', 'intensity': {'forecast': 0, 'index': 'very low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 0}, {'fuel': 'nuclear', 'perc': 0}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 4.3}, {'fuel': 'solar', 'perc': 0}, {'fuel': 'wind', 'perc': 95.7}]}, {'regionid': 2, 'dnoregion': 'SP Distribution', 'shortname': 'South Scotland', 'intensity': {'forecast': 1, 'index': 'very low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 1}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 0}, {'fuel': 'nuclear', 'perc': 48.1}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.5}, {'fuel': 'solar', 'perc': 2.1}, {'fuel': 'wind', 'perc': 48.4}]}, {'regionid': 3, 'dnoregion': 'Electricity North West', 'shortname': 'North West England', 'intensity': {'forecast': 84, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0.6}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 21.2}, {'fuel': 'nuclear', 'perc': 29.7}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.1}, {'fuel': 'solar', 'perc': 1.3}, {'fuel': 'wind', 'perc': 47.1}]}, {'regionid': 4, 'dnoregion': 'NPG North East', 'shortname': 'North East England', 'intensity': {'forecast': 47, 'index': 'very low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 21.9}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 5.3}, {'fuel': 'nuclear', 'perc': 26.3}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.2}, {'fuel': 'solar', 'perc': 6}, {'fuel': 'wind', 'perc': 40.3}]}, {'regionid': 5, 'dnoregion': 'NPG Yorkshire', 'shortname': 'Yorkshire', 'intensity': {'forecast': 166, 'index': 'moderate'}, 'generationmix': [{'fuel': 'biomass', 'perc': 24.6}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 34.7}, {'fuel': 'nuclear', 'perc': 0}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0}, {'fuel': 'solar', 'perc': 2.8}, {'fuel': 'wind', 'perc': 38}]}, {'regionid': 6, 'dnoregion': 'SP Manweb', 'shortname': 'North Wales & Merseyside', 'intensity': {'forecast': 47, 'index': 'very low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0.3}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 11.8}, {'fuel': 'nuclear', 'perc': 14.1}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 8.5}, {'fuel': 'solar', 'perc': 8.4}, {'fuel': 'wind', 'perc': 57}]}, {'regionid': 7, 'dnoregion': 'WPD South Wales', 'shortname': 'South Wales', 'intensity': {'forecast': 266, 'index': 'high'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 67.6}, {'fuel': 'nuclear', 'perc': 0}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0}, {'fuel': 'solar', 'perc': 10.5}, {'fuel': 'wind', 'perc': 21.9}]}, {'regionid': 8, 'dnoregion': 'WPD West Midlands', 'shortname': 'West Midlands', 'intensity': {'forecast': 131, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 1.6}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0.2}, {'fuel': 'gas', 'perc': 32.7}, {'fuel': 'nuclear', 'perc': 13.2}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 2.2}, {'fuel': 'solar', 'perc': 9.7}, {'fuel': 'wind', 'perc': 40.3}]}, {'regionid': 9, 'dnoregion': 'WPD East Midlands', 'shortname': 'East Midlands', 'intensity': {'forecast': 209, 'index': 'moderate'}, 'generationmix': [{'fuel': 'biomass', 'perc': 5.2}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 51.5}, {'fuel': 'nuclear', 'perc': 1.8}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0}, {'fuel': 'solar', 'perc': 9}, {'fuel': 'wind', 'perc': 32.5}]}, {'regionid': 10, 'dnoregion': 'UKPN East', 'shortname': 'East England', 'intensity': {'forecast': 67, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 17}, {'fuel': 'nuclear', 'perc': 21.4}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0}, {'fuel': 'solar', 'perc': 11.2}, {'fuel': 'wind', 'perc': 50.4}]}, {'regionid': 11, 'dnoregion': 'WPD South West', 'shortname': 'South West England', 'intensity': {'forecast': 135, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 34.2}, {'fuel': 'nuclear', 'perc': 23.3}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0}, {'fuel': 'solar', 'perc': 37.9}, {'fuel': 'wind', 'perc': 4.6}]}, {'regionid': 12, 'dnoregion': 'SSE South', 'shortname': 'South England', 'intensity': {'forecast': 202, 'index': 'moderate'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0.9}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 5.5}, {'fuel': 'gas', 'perc': 50.5}, {'fuel': 'nuclear', 'perc': 4.2}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.1}, {'fuel': 'solar', 'perc': 28.1}, {'fuel': 'wind', 'perc': 10.8}]}, {'regionid': 13, 'dnoregion': 'UKPN London', 'shortname': 'London', 'intensity': {'forecast': 89, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 15.9}, {'fuel': 'gas', 'perc': 21.1}, {'fuel': 'nuclear', 'perc': 12.2}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.3}, {'fuel': 'solar', 'perc': 11.1}, {'fuel': 'wind', 'perc': 39.3}]}, {'regionid': 14, 'dnoregion': 'UKPN South East', 'shortname': 'South East England', 'intensity': {'forecast': 104, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 36.4}, {'fuel': 'gas', 'perc': 22.7}, {'fuel': 'nuclear', 'perc': 2.5}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.7}, {'fuel': 'solar', 'perc': 8.9}, {'fuel': 'wind', 'perc': 28.7}]}, {'regionid': 15, 'dnoregion': 'England', 'shortname': 'England', 'intensity': {'forecast': 126, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 4.9}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 5.7}, {'fuel': 'gas', 'perc': 30}, {'fuel': 'nuclear', 'perc': 11.8}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.5}, {'fuel': 'solar', 'perc': 11.8}, {'fuel': 'wind', 'perc': 35.3}]}, {'regionid': 16, 'dnoregion': 'Scotland', 'shortname': 'Scotland', 'intensity': {'forecast': 1, 'index': 'very low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0.7}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 0}, {'fuel': 'nuclear', 'perc': 40.2}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 1.2}, {'fuel': 'solar', 'perc': 1.7}, {'fuel': 'wind', 'perc': 56.2}]}, {'regionid': 17, 'dnoregion': 'Wales', 'shortname': 'Wales', 'intensity': {'forecast': 158, 'index': 'moderate'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0.1}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 40}, {'fuel': 'nuclear', 'perc': 4.7}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 6.8}, {'fuel': 'solar', 'perc': 7.7}, {'fuel': 'wind', 'perc': 40.7}]}, {'regionid': 18, 'dnoregion': 'GB', 'shortname': 'GB', 'intensity': {'forecast': 115, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 4.1}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 4.7}, {'fuel': 'gas', 'perc': 27.5}, {'fuel': 'nuclear', 'perc': 14.3}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 1}, {'fuel': 'solar', 'perc': 10.5}, {'fuel': 'wind', 'perc': 37.8}]}]}]
{'from': '2021-09-29T09:00Z', 'to': '2021-09-29T09:30Z', 'regions': [{'regionid': 1, 'dnoregion': 'Scottish Hydro Electric Power Distribution', 'shortname': 'North Scotland', 'intensity': {'forecast': 0, 'index': 'very low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 0}, {'fuel': 'nuclear', 'perc': 0}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 4.3}, {'fuel': 'solar', 'perc': 0}, {'fuel': 'wind', 'perc': 95.7}]}, {'regionid': 2, 'dnoregion': 'SP Distribution', 'shortname': 'South Scotland', 'intensity': {'forecast': 1, 'index': 'very low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 1}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 0}, {'fuel': 'nuclear', 'perc': 48.1}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.5}, {'fuel': 'solar', 'perc': 2.1}, {'fuel': 'wind', 'perc': 48.4}]}, {'regionid': 3, 'dnoregion': 'Electricity North West', 'shortname': 'North West England', 'intensity': {'forecast': 84, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0.6}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 21.2}, {'fuel': 'nuclear', 'perc': 29.7}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.1}, {'fuel': 'solar', 'perc': 1.3}, {'fuel': 'wind', 'perc': 47.1}]}, {'regionid': 4, 'dnoregion': 'NPG North East', 'shortname': 'North East England', 'intensity': {'forecast': 47, 'index': 'very low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 21.9}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 5.3}, {'fuel': 'nuclear', 'perc': 26.3}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.2}, {'fuel': 'solar', 'perc': 6}, {'fuel': 'wind', 'perc': 40.3}]}, {'regionid': 5, 'dnoregion': 'NPG Yorkshire', 'shortname': 'Yorkshire', 'intensity': {'forecast': 166, 'index': 'moderate'}, 'generationmix': [{'fuel': 'biomass', 'perc': 24.6}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 34.7}, {'fuel': 'nuclear', 'perc': 0}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0}, {'fuel': 'solar', 'perc': 2.8}, {'fuel': 'wind', 'perc': 38}]}, {'regionid': 6, 'dnoregion': 'SP Manweb', 'shortname': 'North Wales & Merseyside', 'intensity': {'forecast': 47, 'index': 'very low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0.3}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 11.8}, {'fuel': 'nuclear', 'perc': 14.1}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 8.5}, {'fuel': 'solar', 'perc': 8.4}, {'fuel': 'wind', 'perc': 57}]}, {'regionid': 7, 'dnoregion': 'WPD South Wales', 'shortname': 'South Wales', 'intensity': {'forecast': 266, 'index': 'high'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 67.6}, {'fuel': 'nuclear', 'perc': 0}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0}, {'fuel': 'solar', 'perc': 10.5}, {'fuel': 'wind', 'perc': 21.9}]}, {'regionid': 8, 'dnoregion': 'WPD West Midlands', 'shortname': 'West Midlands', 'intensity': {'forecast': 131, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 1.6}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0.2}, {'fuel': 'gas', 'perc': 32.7}, {'fuel': 'nuclear', 'perc': 13.2}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 2.2}, {'fuel': 'solar', 'perc': 9.7}, {'fuel': 'wind', 'perc': 40.3}]}, {'regionid': 9, 'dnoregion': 'WPD East Midlands', 'shortname': 'East Midlands', 'intensity': {'forecast': 209, 'index': 'moderate'}, 'generationmix': [{'fuel': 'biomass', 'perc': 5.2}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 51.5}, {'fuel': 'nuclear', 'perc': 1.8}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0}, {'fuel': 'solar', 'perc': 9}, {'fuel': 'wind', 'perc': 32.5}]}, {'regionid': 10, 'dnoregion': 'UKPN East', 'shortname': 'East England', 'intensity': {'forecast': 67, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 17}, {'fuel': 'nuclear', 'perc': 21.4}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0}, {'fuel': 'solar', 'perc': 11.2}, {'fuel': 'wind', 'perc': 50.4}]}, {'regionid': 11, 'dnoregion': 'WPD South West', 'shortname': 'South West England', 'intensity': {'forecast': 135, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 34.2}, {'fuel': 'nuclear', 'perc': 23.3}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0}, {'fuel': 'solar', 'perc': 37.9}, {'fuel': 'wind', 'perc': 4.6}]}, {'regionid': 12, 'dnoregion': 'SSE South', 'shortname': 'South England', 'intensity': {'forecast': 202, 'index': 'moderate'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0.9}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 5.5}, {'fuel': 'gas', 'perc': 50.5}, {'fuel': 'nuclear', 'perc': 4.2}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.1}, {'fuel': 'solar', 'perc': 28.1}, {'fuel': 'wind', 'perc': 10.8}]}, {'regionid': 13, 'dnoregion': 'UKPN London', 'shortname': 'London', 'intensity': {'forecast': 89, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 15.9}, {'fuel': 'gas', 'perc': 21.1}, {'fuel': 'nuclear', 'perc': 12.2}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.3}, {'fuel': 'solar', 'perc': 11.1}, {'fuel': 'wind', 'perc': 39.3}]}, {'regionid': 14, 'dnoregion': 'UKPN South East', 'shortname': 'South East England', 'intensity': {'forecast': 104, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 36.4}, {'fuel': 'gas', 'perc': 22.7}, {'fuel': 'nuclear', 'perc': 2.5}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.7}, {'fuel': 'solar', 'perc': 8.9}, {'fuel': 'wind', 'perc': 28.7}]}, {'regionid': 15, 'dnoregion': 'England', 'shortname': 'England', 'intensity': {'forecast': 126, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 4.9}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 5.7}, {'fuel': 'gas', 'perc': 30}, {'fuel': 'nuclear', 'perc': 11.8}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 0.5}, {'fuel': 'solar', 'perc': 11.8}, {'fuel': 'wind', 'perc': 35.3}]}, {'regionid': 16, 'dnoregion': 'Scotland', 'shortname': 'Scotland', 'intensity': {'forecast': 1, 'index': 'very low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0.7}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 0}, {'fuel': 'nuclear', 'perc': 40.2}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 1.2}, {'fuel': 'solar', 'perc': 1.7}, {'fuel': 'wind', 'perc': 56.2}]}, {'regionid': 17, 'dnoregion': 'Wales', 'shortname': 'Wales', 'intensity': {'forecast': 158, 'index': 'moderate'}, 'generationmix': [{'fuel': 'biomass', 'perc': 0.1}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 0}, {'fuel': 'gas', 'perc': 40}, {'fuel': 'nuclear', 'perc': 4.7}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 6.8}, {'fuel': 'solar', 'perc': 7.7}, {'fuel': 'wind', 'perc': 40.7}]}, {'regionid': 18, 'dnoregion': 'GB', 'shortname': 'GB', 'intensity': {'forecast': 115, 'index': 'low'}, 'generationmix': [{'fuel': 'biomass', 'perc': 4.1}, {'fuel': 'coal', 'perc': 0}, {'fuel': 'imports', 'perc': 4.7}, {'fuel': 'gas', 'perc': 27.5}, {'fuel': 'nuclear', 'perc': 14.3}, {'fuel': 'other', 'perc': 0}, {'fuel': 'hydro', 'perc': 1}, {'fuel': 'solar', 'perc': 10.5}, {'fuel': 'wind', 'perc': 37.8}]}]}

    regionid  ... intensity.index
0          1  ...        very low
1          2  ...        very low
2          3  ...             low
3          4  ...        very low
4          5  ...        moderate
5          6  ...        very low
6          7  ...            high
7          8  ...             low
8          9  ...        moderate
9         10  ...             low
10        11  ...             low
11        12  ...        moderate
12        13  ...             low
13        14  ...             low
14        15  ...             low
15        16  ...        very low
16        17  ...        moderate
17        18  ...             low

[18 rows x 6 columns]

### Exercise - upload a file from your local drive

Visit the Kent and Medway Air Quality site: https://kentair.org.uk/

Collect a data file containing data on Ozone levels in Dover:

Open the site
Go to the Data page  
Launch the data selector tool  
Select:
*  Automatic monitoring data
*  Measurement data and simple statistics
*  Ozone
*  Daily mean
*  This month
*  Thurrock
*  Thurrock

Click on Download CSV

This should be downloaded into your Downloads folder.

NOW

Write a function that will allow you to upload the file and then read its contents into a dataframe.

Display the dataframe and compare the contents with the output on the site you took the data from.

In [31]:
import pandas as pd
from google.colab import files
import io
def get_data():
  # upload a set of chosen files then read a specified file
  # !rm NO2-daily-mean-2014-2021-Swale-Newington.csv
  uploaded = files.upload()
  df = pd.read_csv(io.BytesIO(uploaded['data-selector-export.csv']))
  return df

get_data()

# The code first removes any existing occurrences of the file we want to upload (!rm ...) This is to stop the problem of Google adding (1) to the file name
# Then the line df = pd.read_csv(io.BytesIO(uploaded['NO2-daily-mean-2014-2021-Swale-Newington.csv'])) reads a version of the csv file that has been converted into text.

Saving data-selector-export.csv to data-selector-export (5).csv

    Unnamed: 0  Thurrock Unnamed: 2
0         Date     Ozone     Status
1   01/09/2021  49.79272    P µg/m³
2   02/09/2021  55.98770    P µg/m³
3   03/09/2021  65.88305    P µg/m³
4   04/09/2021  67.12204    P µg/m³
5   05/09/2021  59.63817    P µg/m³
6   06/09/2021  36.62109    P µg/m³
7   07/09/2021  63.39674    P µg/m³
8   08/09/2021  65.66684    P µg/m³
9   09/09/2021  37.61894    P µg/m³
10  10/09/2021  45.19429    P µg/m³
11  11/09/2021    nodata    P µg/m³
12  12/09/2021    nodata    P µg/m³
13  24/09/2021  30.81187    P µg/m³
14  25/09/2021  18.12761    P µg/m³
15  26/09/2021  41.93465    P µg/m³
16  27/09/2021  53.55960    P µg/m³
17  28/09/2021  52.27071    P µg/m³